apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.frontend.service.port }}
  selector:
    name: frontend
