---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
spec:
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: quote
  template:
    metadata:
      labels:
        name: quote
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java"]
          args: ["-jar", "quotes.jar"]
          ports:
            - containerPort: 8081
          livenessProbe:
            tcpSocket:
              port: 8082
          env:
            {{- toYaml .Values.quote.env_variables | nindent 12 }}
