---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-assets
spec:
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: static-assets
  template:
    metadata:
      labels:
        name: static-assets
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python3"]
          args: ["serve.py"]
          ports:
            - containerPort: 8000
